---
title: "Advent of Code 2021 - Day 3"
author: "Gus Lipkin ~ github.com/guslipkin/AdventOfCode2021"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
library(compositions)
```

```{r}
# part 1
dt <- data.frame(fread("input.txt", sep = "\n", colClasses = c("character")))
dt <- tidyr::separate(dt, "V1", paste0("V", 1:13), sep = "", convert = TRUE)

get_mode <- function(x)
  return(names(sort(table(x), decreasing = T, na.last = T)[1]))
o <- c()
for(i in 2:13)
  o <- append(o, get_mode(dt[,i]))

o <- unbinary(paste(o, collapse = ""))

get_mode <- function(x)
  return(names(sort(table(x), na.last = T)[1]))
c <- c()
for(i in 2:13)
  c <- append(c, get_mode(dt[,i]))
c <- unbinary(paste(c, collapse = ""))

o * c
```

```{r}
# part 2
rbenchmark::benchmark("test" = {
dtM <- data.frame(fread("input.txt", sep = "\n", colClasses = c("character")))
dtM <- tidyr::separate(dtM, "V1", paste0("V", 1:13), sep = "", convert = TRUE)
dtM <- dtM %>% select(-"V1")
dt <- dtM

get_modeMax <- function(x){
  temp <- sort(table(x), decreasing = T, na.last = T)
  ifelse(temp[1] == temp[2], return(1), names(temp[1]))
}
o <- c()

for(i in 1:12) {
  dt <- dt %>%
    filter_at(i, all_vars(.==get_modeMax(dt[,i])))
  if(nrow(dt) == 1) {
    oxygen <- paste(as.character(dt[1,]), collapse = "")
    break
  }
}

dt <- dtM
get_modeMin <- function(x){
  temp <- sort(table(x), na.last = T)
  ifelse(temp[1] == temp[2], return(0), names(temp[1]))
}
c <- c()

for(i in 1:12) {
  dt <- dt %>%
    filter_at(i, all_vars(.==get_modeMin(dt[,i])))
  if(nrow(dt) == 1) {
    co2 <- paste(as.character(dt[1,]), collapse = "")
    break
  }
}

unbinary(oxygen) * unbinary(co2)
}, replications = 100)
```

