---
title: "Advent of Code 2021 - Day 10"
author: "Gus Lipkin ~ github.com/guslipkin/AdventOfCode2021"
output: html_notebook
---

```{r}
library(stringr)

dt <- data.table::fread("input.txt", header = FALSE, colClasses = "character")
```

```{r}
# part 1
dt2 <- dt

monkeyBall <- function(x, n) {
  x <- str_replace_all(x, "\\(\\)|\\[\\]|\\{\\}|\\<\\>", "")
  if(nchar(x) == n) {
    t <- as.character(str_split(str_replace_all(x, "[\\(\\[\\{\\<]", ""),
                   "",
                   simplify = TRUE)[1,])
    t <- t[1]
    return(t)
  }
  return(monkeyBall(x, nchar(x)))
}

t <- c()
for(r in 1:nrow(dt2)) {
  x <- dt2[r,1]
  n <- nchar(x)
  t <- append(t, monkeyBall(x, n))
}
t <- table(t)
if (is.na(t[")"]))
  t[")"] <- 0
if (is.na(t["]"]))
  t["]"] <- 0
if (is.na(t["}"]))
  t["}"] <- 0
if (is.na(t[">"]))
  t[">"] <- 0
(3 * t[")"]) + (57 * t["]"]) + (1197 * t["}"]) + (25137 * t[">"])
```


```{r}
# part 2
dt2 <- dt

monkeyBall <- function(x, n) {
  x <- str_replace_all(x, "\\(\\)|\\[\\]|\\{\\}|\\<\\>", "")
  if(nchar(x) == n) {
    if(!grepl("\\)|\\]|\\}|\\>", x, perl = TRUE))
      return(x)
    return("")
  }
  return(monkeyBall(x, nchar(x)))
}

t <- c()
for(r in 1:nrow(dt2)) {
  x <- dt2[r,1]
  n <- nchar(x)
  t <- append(t, monkeyBall(x, n))
}
t <- t[nchar(t) > 0]
s <- c()
for(i in t) {
  miniS <- 0
  miniT <- rev(str_split(i, "", simplify = TRUE)[1,])
  for(l in miniT) {
    miniS <- (5 * miniS) + case_when(l == "(" ~ 1,
                                     l == "[" ~ 2,
                                     l == "{" ~ 3,
                                     l == "<" ~ 4)
  }
  s <- append(s, miniS)
}
s <- s[!is.na(s)]
median(s)
```

